<?php

use Illuminate\Database\Seeder;

class VinsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('vins')->insert([
            [
                'produ_id' => '1',
                'appel_id' => '2',
                'frmt_id' => '4',
                'regn_id' => '1',
                'prix_id' => '1',
                'condi_id' => '2',
                'nom' => 'Château Cambon la Pelouse',
                'descriptionText' => 'Figurant parmi les plus anciens châteaux du Médoc, la propriété expédie ses vins en Angleterre dès le XVIIe siècle et en Hollande à partir du XVIIIe siècle. Sous la révolution, le château a appartenu à la famille de Cambon, à qui il doit son nom. Le vignoble, entièrement décimé lors du gel de 1956 et partiellement transformé alors en champ céréalier, a été replanté en 1975 et a une moyenne d’âge d’une trentaine d’années.
                
                Il est très bien situé, en hauteur entre deux crus classés, Giscours et Cantemerle, près de Macau sur la route de Margaux et Pauillac, au bord de la Gironde. Annick et Jean-Pierre Marie, qui vient de la grande distribution, le rachètent en 1996 et mettent tout en oeuvre pour lui redonner son lustre en réalisant d’importants investissements. Le domaine possède aujourd’hui 60 hectares de vignes au total, plantées avec une densité de 5000 à 7000 pieds / ha sur un sol de graves maigres sur une partie de la propriété et de grosses graves du quaternaire ailleurs.',
                'alcool' => '13.5°',
                'apogee' => '2022 - 2038',
                'millesime' => '2015',
                'photoUrl' => null,
                'estBio' => false,
                'estVds' => false,
                'cotation' => null,
                'classement' => 'Cru Bourgeois supérieur',
                'stock' => 1000,
                'created_at' => null,
            ],
            [
                'produ_id' => '2',
                'appel_id' => '2',
                'frmt_id' => '1',
                'regn_id' => '1',
                'prix_id' => '2',
                'condi_id' => '3',
                'nom' => 'Château Sénéjac',
                'descriptionText' => 'Sénéjac et le vin, c\'est une longue histoire. Au 16ème siècle, selon toute vraisemblance, on y produisait déjà du vin. Au milieu de 19ème, la production était de 100 000 bouteilles, soit la moitié de ce qui s\'y fait aujourd\'hui. Depuis 1999, ce Cru Bourgeois est entre les mains de la famille Bignon-Cordier qui possède également le château Talbot, un Grand Cru classé de Saint-Julien.',
                'alcool' => '13°',
                'apogee' => '2020 - 2035',
                'millesime' => '2015',
                'photoUrl' => null,
                'estBio' => false,
                'estVds' => false,
                'cotation' => null,
                'classement' => 'Cru Bourgeois supérieur',
                'stock' => 1000,
                'created_at' => null,
            ],
            [
                'produ_id' => '3',
                'appel_id' => '2',
                'frmt_id' => '1',
                'regn_id' => '1',
                'prix_id' => '3',
                'condi_id' => '1',
                'nom' => 'Château Charmail',
                'descriptionText' => 'Tirant son nom d\'une famille d\'origine bretonne qui s’installe en Médoc au 16ème siècle, les Trevey de Charmail, ce domaine viticole se fait connaître au début du 18ème. Propriétaire de Château Mayne-Vieil à Fronsac, l’ingénieur agronome Roger Sèze achète la propriété entre 1980 et 1981, et reconstruit le chai et le château.',
                'alcool' => '13.5°',
                'apogee' => '2020 - 2035',
                'millesime' => '2015',
                'photoUrl' => null,
                'estBio' => false,
                'estVds' => false,
                'cotation' => null,
                'classement' => 'Cru Bourgeois supérieur',
                'stock' => 1000,
                'created_at' => null,
            ],
            [
                'produ_id' => '4',
                'appel_id' => '2',
                'frmt_id' => '1',
                'regn_id' => '1',
                'prix_id' => '4',
                'condi_id' => '1',
                'nom' => 'Château Sociando-Mallet',
                'descriptionText' => 'Ce Château est régulièrement un de nos best-sellers. Cette propriété, située tout au nord du Médoc, a réussi en l\'espace de 40 ans à se hisser parmi l\'élite des vins rouges de Bordeaux. Ceci grâce au travail inlassable de son propriétaire, M. Jean Gautreau. Lors de nombreuses dégustations à l\'aveugle, il surclasse régulièrement de nombreux grands crus classés prestigieux.',
                'alcool' => '13.5°',
                'apogee' => '2021 - 2039',
                'millesime' => '2014',
                'photoUrl' => null,
                'estBio' => false,
                'estVds' => false,
                'cotation' => null,
                'classement' => null,
                'stock' => 1000,
                'created_at' => null,
            ],
            [
                'produ_id' => '4',
                'appel_id' => '2',
                'frmt_id' => '1',
                'regn_id' => '1',
                'prix_id' => '10',
                'condi_id' => '1',
                'nom' => 'Château Sociando-Mallet',
                'descriptionText' => 'Ce Château est régulièrement un de nos best-sellers. Cette propriété, située tout au nord du Médoc, a réussi en l\'espace de 40 ans à se hisser parmi l\'élite des vins rouges de Bordeaux. Ceci grâce au travail inlassable de son propriétaire, M. Jean Gautreau. Lors de nombreuses dégustations à l\'aveugle, il surclasse régulièrement de nombreux grands crus classés prestigieux.',
                'alcool' => '13.5°',
                'apogee' => '2017 - 2034',
                'millesime' => '2011',
                'photoUrl' => null,
                'estBio' => false,
                'estVds' => false,
                'cotation' => "Parker : 91/100",
                'classement' => null,
                'stock' => 1000,
                'created_at' => null,
            ],
            [
                'produ_id' => '4',
                'appel_id' => '2',
                'frmt_id' => '1',
                'regn_id' => '1',
                'prix_id' => '11',
                'condi_id' => '1',
                'nom' => 'Château Sociando-Mallet',
                'descriptionText' => 'Ce Château est régulièrement un de nos best-sellers. Cette propriété, située tout au nord du Médoc, a réussi en l\'espace de 40 ans à se hisser parmi l\'élite des vins rouges de Bordeaux. Ceci grâce au travail inlassable de son propriétaire, M. Jean Gautreau. Lors de nombreuses dégustations à l\'aveugle, il surclasse régulièrement de nombreux grands crus classés prestigieux.',
                'alcool' => '13.5°',
                'apogee' => '2021 - 2039',
                'millesime' => '2015',
                'photoUrl' => null,
                'estBio' => false,
                'estVds' => false,
                'cotation' => "Suckling : 92-93/100",
                'classement' => null,
                'stock' => 1000,
                'created_at' => null,
            ],
            [
                'produ_id' => '5',
                'appel_id' => '1',
                'frmt_id' => '1',
                'regn_id' => '2',
                'prix_id' => '5',
                'condi_id' => '3',
                'nom' => 'Champagne Charles Mignon 1er Cru "Premium Reserve Brut"',
                'descriptionText' => 'La maison de Champagne Charles Mignon est l\'une des rares maisons à caractère familial à être membre de l\'Union de Maisons de Champagne. Quatre générations ont perpétué avec passion et savoir-faire les plus nobles traditions champenoises. Bruno, l\'arrière-petit-fils, a repris le flambeau en 1995. ',
                'alcool' => '12°',
                'apogee' => '',
                'millesime' => '0',
                'photoUrl' => null,
                'estBio' => false,
                'estVds' => false,
                'cotation' => null,
                'classement' => null,
                'stock' => 1000,
                'created_at' => null,
            ],
            [
                'produ_id' => '6',
                'appel_id' => '1',
                'frmt_id' => '1',
                'regn_id' => '3',
                'prix_id' => '6',
                'condi_id' => '2',
                'nom' => 'Champagne Charles Mignon 1er Cru "Premium Reserve Brut"',
                'descriptionText' => 'Le Domaine Chandon de Briailles s\'étend sur 13 hectares de vignes en Côte de Beaune, en Bourgogne. Propriété familiale depuis 1834, le domaine est géré par le comte et la comtesse Aymard-Claude de Nicolay et leurs enfants. Le comte de Nicolay l\'avait hérité de sa grand-mère, la comtesse Chandon de Briailles, apparentée à la maison de Champagne Moët et Chandon.

                Le Domaine bourguignon Chandon de Briailles privilégie la tradition, avec une forte proportion de vendange entière et surtout pratiquement pas de fûts chêne neufs dans l\'élevage. Dans leur jeunesse, les vins semblent plutôt peu expressifs, mais gagnent beaucoup de complexité après quelques années de vieillissement. Les vins de Chandon de Briailles jouent surtout dans un registre de finesse et d\'élégance plutôt que de puissance.',
                'alcool' => '13°',
                'apogee' => '2022 - 2043',
                'millesime' => '2013',
                'photoUrl' => null,
                'estBio' => false,
                'estVds' => true,
                'cotation' => null,
                'classement' => null,
                'stock' => 1000,
                'created_at' => null,
            ],
            [
                'produ_id' => '7',
                'appel_id' => '4',
                'frmt_id' => '1',
                'regn_id' => '4',
                'prix_id' => '7',
                'condi_id' => '4',
                'nom' => 'Châteauneuf-du-Pape «Cuvée de mon Aïeul»',
                'descriptionText' => '"Une des top-propriétés sur Châteauneuf-du-Pape est celle des deux frères, Thierry et Jean-Pierre Usseglio. Leur cave est située au nord du village, juste à côté des murs des ruines du palais du pape. Ils ont 38 hectares de vignes et produisent trois cuvées de vin rouge dans les meilleurs millésimes. Leur cuvée classique ou tradition est un assemblage principalement de Grenache, avec un peu de Syrah, de Cinsault et de Mourvèdre. La Cuvée de mon Aïeul n’est pas élevée en fûts, mais en cuves. Celle-ci provient de très vieilles vignes (à peu près âgées de 85 ans), avec des rendements très bas. La Réserve des deux Frères tend vers une expression plus moderne de Châteauneuf-du-Pape, avec environ 50% de vieillissement en petits fûts, 20% en cuve et 30% dans des demi-muids de 600 litres." The Wine Advocate – octobre 2011',
                'alcool' => '15°',
                'apogee' => '2016 - 2026',
                'millesime' => '2014',
                'photoUrl' => null,
                'estBio' => false,
                'estVds' => true,
                'cotation' => "Parker : 94/100
                Bettane+Desseauve: Coup de Coeur",
                'classement' => null,
                'stock' => 1000,
                'created_at' => null,
            ],
            [
                'produ_id' => '8',
                'appel_id' => '4',
                'frmt_id' => '1',
                'regn_id' => '5',
                'prix_id' => '8',
                'condi_id' => '3',
                'nom' => 'Greco di Tufo Bianco "Vigna Cicogna" DOCG',
                'descriptionText' => '" Technique de vinification : les raisins sont vendangés à la main et amenés à la cave dans des cagettes de 20 kg. Les grappes subissent une macération à froid et un pressage en douceur. Les moûts fermentent à une température de 18° durant environ 25 à 35 jours.

                Température de service : Ce Greco di Tufo devrait être servi à une température de 8-10 °C.
                
                Notes de dégustation : De couleur légèrement dorée, le Greco di Tufo est un vin aromatique, avec un bouquet fruité intense, sec et très équilibré. Ses arômes sont uniques avec une touche particulière d\'amande amère.
                
                Accords mets-vins : Ce vin est particulièrement recommandé en apéritif, sur des viandes blanches, du fromage, ainsi que sur des sauces épicées. ',
                'alcool' => '13.5°',
                'apogee' => '2016 - 2023',
                'millesime' => '2015',
                'photoUrl' => null,
                'estBio' => false,
                'estVds' => true,
                'cotation' => "Vinous : 91+/100",
                'classement' => null,
                'stock' => 1000,
                'created_at' => null,
            ],
            [
                'produ_id' => '9',
                'appel_id' => '5',
                'frmt_id' => '1',
                'regn_id' => '1',
                'prix_id' => '9',
                'condi_id' => '1',
                'nom' => 'Château Potensac',
                'descriptionText' => '

                Depuis plusieurs siècles (!), le Château Potensac est propriété de la famille Delon, également propriétaire du Château Léoville-Las-Cases à St-Julien. Le Château Potensac bénéficie, tant à la vigne, que pour la vinification ou l\'élevage, des mêmes soins méticuleux que pour son grand frère, le Château Léoville-Las-Cases.
                
                Les vignes du Château Potensac sont d\'un âge moyen élevé de 30 ans sur des coteaux graveleux. Les vins, dans le plus pur style médocain, se caractérisent par une grande régularité de qualité, une capacité certaine au vieillissement, une couleur toujours soutenue, un bouquet strict mais noble, liant richesse de sève et équilibre, avec des touches de finesse et de distinction, reflet d\'un terroir particulier.
                
                D\'ailleurs, le Château Potensac est le seul Château, lors du récent classement des Crus Bourgeois de l\'appellation Médoc, à avoir été classé Cru Bourgeois Exceptionnel.
                ',
                'alcool' => '13°',
                'apogee' => '2021 - 2038',
                'millesime' => '2015',
                'photoUrl' => null,
                'estBio' => false,
                'estVds' => true,
                'cotation' => null,
                'classement' => 'Cru Bourgeois exceptionnel',
                'stock' => 1000,
                'created_at' => null,
            ],
            [
                'produ_id' => '10',
                'appel_id' => '1',
                'frmt_id' => '1',
                'regn_id' => '6',
                'prix_id' => '12',
                'condi_id' => '2',
                'nom' => 'Ribera Del Duero DO Alion - (Vega Sicilia)',
                'descriptionText' => 'Vin élaboré à partir de la variété Tinto fino. Il est vendangé à la main dans des caisses de 12 kg et est amené immédiatement à la cave pour son entrée sur les tables de sélection. Les fermentations sont menées à bien dans des cuves en bois avec un contrôle de température jusqu\'à obtenir une bonne extraction polyphénolique qui apportera la robe généreuse et la structure ferme qui constituent partie de la personnalité de ce vin et enfin un élevage en fût de 14 à 20 mois, dépendant des caractéristiques du cru, est réalisé dans sa totalité dans des nouvelles barriques bordelaises en chêne français. Ces barriques, des entreprises les plus prestigieuses de Bordeaux (Radoux, Taranssaud, Saury et Vicard), supposent un investissement en chêne important, car, millésime après millésime, tout le vin qui est élaboré chez Alión restera dans des nouvelles barriques qui, après son abandon pour être mis en bouteilles, ne seront pas réutilisées par la cave.',
                'alcool' => '14.5°',
                'apogee' => '2016 - 2023',
                'millesime' => '2013',
                'photoUrl' => null,
                'estBio' => false,
                'estVds' => true,
                'cotation' => null,
                'classement' => null,
                'stock' => 1000,
                'created_at' => '2019-03-06 00:00:00',
            ],
            [
                'produ_id' => '11',
                'appel_id' => '6',
                'frmt_id' => '2',
                'regn_id' => '7',
                'prix_id' => '13',
                'condi_id' => '3',
                'nom' => 'Chant des Resses',
                'descriptionText' => 'Le nez, floral et fruité, allie finesse et puissance sur une remarquable touche de minéralité typique du terroir. En bouche, l\'attaque est puissante et soutenue par la richesse. L\'évolution présente une belle rondeur avec des notes fruitées. En finale, l\'intensité et la tenue des arômes soulignent l\'équilibre et l\'harmonie de ce vin. ',
                'alcool' => '12.2°',
                'apogee' => '',
                'millesime' => '2018',
                'photoUrl' => null,
                'estBio' => false,
                'estVds' => true,
                'cotation' => null,
                'classement' => 'Grand Cru',
                'stock' => 1000,
                'created_at' => null,
            ],
        ]);
    }
}
